version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: glances_web_1
      APP_PORT: 61208

  web:
    image: nicolargo/glances:3.3.1.1
    restart: on-failure
    stop_grace_period: 1m
    init: true
    environment:
      - TERM=linux
      - TERMINFO=/etc/terminfo
